Repository the-NDD/Gomterview-BE, pull requests merged in 2024-02, with the labels that each got.

#9 [VideoRelation] 연관영상 관련 기능 구현
  src/question/fixture/question.fixture.ts
  src/util/test.util.ts
  src/video/constant/videoVisibility.ts
  src/video/controller/video.controller.spec.ts
  src/video/controller/video.controller.ts
  src/video/dto/MemberVideoResponse.ts
  src/video/dto/RelatableVideoResponse.ts
  src/video/dto/singleVideoResponse.ts
  src/video/dto/updateVideoRequest.ts
  src/video/dto/videoDetailResponse.ts
  src/video/entity/video.ts
  src/video/entity/videoRelation.ts
  src/video/fixture/video.fixture.ts
  src/video/repository/video.repository.ts
  src/video/repository/videoRelation.repository.ts
  src/video/service/video.service.spec.ts
  src/video/service/video.service.ts
  src/video/video.module.ts
Labels: enhancement, feature, test

#11 fix: 실행시 videoRelation메타데이터 부족으로 인한 VideoRelation을 설정파일에 추가
  src/config/typeorm.config.ts
Labels: bug

#12 [NDD-417] IDrive 삭제 로직 구현 후 비디오 삭제가 되지 않는 버그 해결
  src/util/idrive.util.ts
  src/video/service/video.service.ts
Labels: bug

#13 fix: 공개 영상을 최신순으로 조회하게 수정 && VidelDetailResponse에 visibility추가
  src/video/dto/videoDetailResponse.ts
  src/video/repository/video.repository.ts
Labels: bug

#14 Feature/video relation
  src/video/dto/MemberVideoResponse.ts
  src/video/dto/updateVideoRequest.ts
  src/video/repository/video.repository.ts
  src/video/repository/videoRelation.repository.ts
  src/video/service/video.service.spec.ts
  src/video/service/video.service.ts
Labels: bug, enhancement

#16 fix: 삭제로직에서 split이 undefined로 나오는 문제를 Replace로 바꿔 해결
  src/video/service/video.service.ts
Labels: bug

#17 [v 1.3.0]
  src/answer/controller/answer.controller.ts
  src/answer/exception/answer.exception.ts
  src/category/exception/category.exception.ts
  src/config/typeorm.config.ts
  src/constant/constant.ts
  src/member/controller/member.controller.ts
  src/member/exception/member.exception.ts
  src/question/controller/question.controller.spec.ts
  src/question/controller/question.controller.ts
  src/question/dto/updateIndexInWorkbookRequest.ts
  src/question/entity/question.ts
  src/question/exception/question.exception.ts
  src/question/fixture/question.fixture.ts
  src/question/repository/question.repository.ts
  src/question/service/question.service.spec.ts
  src/question/service/question.service.ts
  src/token/exception/token.exception.ts
  src/util/exception.util.ts
  src/util/idrive.util.ts
  src/util/test.util.ts
  src/video/constant/videoVisibility.ts
  src/video/controller/video.controller.spec.ts
  src/video/controller/video.controller.ts
  src/video/dto/MemberVideoResponse.ts
  src/video/dto/RelatableVideoResponse.ts
  src/video/dto/singleVideoResponse.ts
  src/video/dto/updateVideoIndexRequest.ts
  src/video/dto/updateVideoRequest.ts
  src/video/dto/videoDetailResponse.ts
  src/video/entity/video.ts
  src/video/entity/videoRelation.ts
  src/video/exception/video.exception.ts
  src/video/fixture/video.fixture.ts
  src/video/repository/video.repository.ts
  src/video/repository/videoRelation.repository.ts
  src/video/service/video.service.spec.ts
  src/video/service/video.service.ts
  src/video/video.module.ts
  src/workbook/controller/workbook.controller.ts
  src/workbook/exception/workbook.exception.ts
Labels: feature, test

#24 [NDD-420] Response DTO에서 createdAt을 number타입에서 파싱된 string으로 반환하게 수정
  src/util/util.ts
  src/video/dto/MemberVideoResponse.ts
  src/video/dto/RelatableVideoResponse.ts
  src/video/dto/singleVideoResponse.ts
  src/video/dto/videoDetailResponse.ts
Labels: enhancement

#25 [ Event/Workbook ] Workbook 도메인의 카테고리 로직을 이벤트화
  package-lock.json
  package.json
  src/app.module.ts
  src/category/service/category.service.ts
  src/member/repository/member.repository.ts
  src/util/test.util.ts
  src/video/fixture/video.fixture.ts
  src/video/service/video.service.spec.ts
  src/video/service/video.service.ts
  src/workbook/dto/workbookResponse.ts
  src/workbook/entity/workbook.ts
  src/workbook/fixture/workbook.fixture.ts
  src/workbook/repository/workbook.repository.ts
  src/workbook/service/workbook.service.spec.ts
  src/workbook/service/workbook.service.ts
  src/workbook/workbook.module.ts
Labels: enhancement, test

#27 [ Event/answer] Answer도메인 분리/이벤트 기반으로 로직을 수행하게 수정
  src/answer/answer.module.ts
  src/answer/controller/answer.controller.spec.ts
  src/answer/entity/answer.ts
  src/answer/event/clear.default.answer.event.ts
  src/answer/event/update.answer.origin.event.ts
  src/answer/fixture/answer.fixture.ts
  src/answer/repository/answer.repository.ts
  src/answer/service/answer.event.handler.ts
  src/answer/service/answer.service.spec.ts
  src/answer/service/answer.service.ts
  src/question/dto/questionResponse.ts
  src/question/entity/question.ts
  src/question/event/check.question.tobe.origin.event.ts
  src/question/event/find.question.origin.event.ts
  src/question/event/find.question.to.validate.workbook.ownership.event.ts
  src/question/event/update.default.answer.event.ts
  src/question/event/validate.default.answers.existence.event.ts
  src/question/event/validate.question.existence.event.ts
  src/question/event/validate.question.origin.event.ts
  src/question/exception/question.exception.ts
  src/question/fixture/question.fixture.ts
  src/question/question.module.ts
  src/question/repository/question.repository.ts
  src/question/service/question.event.handler.ts
  src/question/service/question.service.spec.ts
  src/question/service/question.service.ts
  src/workbook/event/validate.workbook.ownership.event.ts
  src/workbook/service/workbook.event.handler.ts
  src/workbook/service/workbook.service.spec.ts
  src/workbook/service/workbook.service.ts
  src/workbook/workbook.module.ts
Labels: enhancement
